using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebMedical.Migrations
{
    /// <inheritdoc />
    public partial class AddUserProfileRelationToUserLogin : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers""
                ADD COLUMN IF NOT EXISTS ""UserProfileId_fk"" integer NOT NULL DEFAULT 0;");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ""UserProfile"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""UserLoginId_pk"" text NULL,
                ""Guid"" uuid NOT NULL,
                ""SocialSecurityNumber"" text NOT NULL,
                ""Name"" text NOT NULL,
                ""MiddleName"" text NOT NULL,
                ""LastName"" text NOT NULL,
                ""LastName2"" text NOT NULL,
                ""DateOfBirth"" date NOT NULL,
                ""Phone"" text NOT NULL,
                ""FisicalAddress"" text NOT NULL,
                ""FisicalAddressLine2"" text NOT NULL,
                ""Town"" integer NOT NULL,
                ""State"" integer NOT NULL,
                ""Zipcode"" integer NOT NULL,
                ""PostalAddress"" text NOT NULL,
                ""PostalAddressLine2"" text NOT NULL,
                ""IsActive"" boolean NOT NULL,
                ""IsRegister"" boolean NOT NULL,
                CONSTRAINT ""PK_UserProfile"" PRIMARY KEY (""Id"")
            );");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AspNetUsers_UserProfileId_fk""
                ON ""AspNetUsers"" (""UserProfileId_fk"");");

            migrationBuilder.Sql(@"DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_AspNetUsers_UserProfile_UserProfileId_fk'
                ) THEN
                    ALTER TABLE ""AspNetUsers""
                    ADD CONSTRAINT ""FK_AspNetUsers_UserProfile_UserProfileId_fk""
                    FOREIGN KEY (""UserProfileId_fk"")
                    REFERENCES ""UserProfile"" (""Id"")
                    ON DELETE CASCADE;
                END IF;
            END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AspNetUsers_UserProfile_UserProfileId_fk",
                table: "AspNetUsers");

            migrationBuilder.DropTable(
                name: "UserProfile");

            migrationBuilder.DropIndex(
                name: "IX_AspNetUsers_UserProfileId_fk",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "UserProfileId_fk",
                table: "AspNetUsers");
        }
    }
}
